# Terraform configuration for OpenClaw instance: river
# Generated by create-instance.sh

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile

  default_tags {
    tags = {
      Project     = "openclaw-river"
      Instance    = "river"
      Environment = "prod"
      ManagedBy   = "terraform"
    }
  }
}

module "openclaw" {
  source = "../../terraform/modules/openclaw"

  # Required: Your allowed SSH IP
  allowed_ssh_cidr = var.allowed_ssh_cidr

  # Naming
  project_name = "openclaw-river"
  environment  = "prod"

  # Network
  aws_region               = var.aws_region
  vpc_cidr                 = var.vpc_cidr
  public_subnet_cidr       = var.public_subnet_cidr
  availability_zone_suffix = "a"

  # EC2
  instance_type    = var.instance_type
  root_volume_size = var.root_volume_size
  root_volume_type = "gp3"

  # SSH Key
  create_ssh_key       = true
  ssh_private_key_path = var.ssh_private_key_path
  ssh_public_key_path  = var.ssh_public_key_path

  # User Data
  enable_user_data  = true
  openclaw_user     = var.openclaw_user
  install_node      = true
  install_openclaw  = true

  # Monitoring
  enable_detailed_monitoring = true
  enable_ssm                 = true

  # Additional Tags
  additional_tags = var.additional_tags
}

# Outputs
output "instance_public_ip" {
  description = "Public IP address of the OpenClaw instance"
  value       = module.openclaw.instance_public_ip
}

output "ssh_connection_command" {
  description = "Command to SSH into the instance"
  value       = module.openclaw.ssh_connection_command
}

output "ssh_tunnel_command" {
  description = "Command to create SSH tunnel for gateway access"
  value       = module.openclaw.ssh_tunnel_command
}

output "gateway_local_url" {
  description = "URL to access gateway after SSH tunnel"
  value       = module.openclaw.gateway_local_url
}

output "security_reminder" {
  description = "Security best practices reminder"
  value       = module.openclaw.security_reminder
}
