#!/bin/bash
# Create a new moltbot instance

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <instance-name>"
    echo "Example: $0 alfred"
    exit 1
fi

INSTANCE_NAME="$1"
INSTANCE_DIR="$PROJECT_ROOT/instances/$INSTANCE_NAME"

# Validate instance name
if [[ ! "$INSTANCE_NAME" =~ ^[a-z0-9-]+$ ]]; then
    echo -e "${RED}Error: Invalid instance name${NC}"
    echo "Instance name must contain only lowercase letters, numbers, and hyphens"
    exit 1
fi

if [[ -d "$INSTANCE_DIR" ]]; then
    echo -e "${RED}Error: Instance '$INSTANCE_NAME' already exists${NC}"
    exit 1
fi

echo -e "${CYAN}Creating new moltbot instance: ${NC}${GREEN}$INSTANCE_NAME${NC}"
echo ""

# Create instance directory
mkdir -p "$INSTANCE_DIR"

# Create instance.yaml
echo -e "${YELLOW}→${NC} Creating instance.yaml"
cat > "$INSTANCE_DIR/instance.yaml" <<EOF
# Moltbot Instance Configuration: $INSTANCE_NAME

name: $INSTANCE_NAME
display_name: $(echo ${INSTANCE_NAME^})

# AWS Configuration
aws:
  profile: noldor
  region: af-south-1

# Instance Configuration
instance:
  type: t3.small
  volume_size: 30

# Moltbot Configuration
moltbot:
  user: clawd
  gateway_port: 18789

# SSH Configuration
ssh:
  key_name: ${INSTANCE_NAME}_key
  key_path: ~/.ssh/${INSTANCE_NAME}_key.pem
  public_key_path: ~/.ssh/${INSTANCE_NAME}_key.pub

# Networking (update allowed_ssh_cidr in terraform.tfvars!)
network:
  allowed_ssh_cidr: "YOUR_IP/32"
  vpc_cidr: "10.100.0.0/16"
  subnet_cidr: "10.100.1.0/24"

# Paths
paths:
  backup_dir: ~/.${INSTANCE_NAME}-backups

# Tags
tags:
  Owner: your-name
  Project: moltbot-${INSTANCE_NAME}
  Environment: prod
EOF

# Create main.tf
echo -e "${YELLOW}→${NC} Creating main.tf"
cat > "$INSTANCE_DIR/main.tf" <<'MAINEOF'
# Terraform configuration for moltbot instance: INSTANCE_NAME_PLACEHOLDER
# Generated by create-instance.sh

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile

  default_tags {
    tags = {
      Project     = "moltbot-INSTANCE_NAME_PLACEHOLDER"
      Instance    = "INSTANCE_NAME_PLACEHOLDER"
      Environment = "prod"
      ManagedBy   = "terraform"
    }
  }
}

module "moltbot" {
  source = "../../terraform/modules/moltbot"

  # Required: Your allowed SSH IP
  allowed_ssh_cidr = var.allowed_ssh_cidr

  # Naming
  project_name = "moltbot-INSTANCE_NAME_PLACEHOLDER"
  environment  = "prod"

  # Network
  aws_region               = var.aws_region
  vpc_cidr                 = var.vpc_cidr
  public_subnet_cidr       = var.public_subnet_cidr
  availability_zone_suffix = "a"

  # EC2
  instance_type    = var.instance_type
  root_volume_size = var.root_volume_size
  root_volume_type = "gp3"

  # SSH Key
  create_ssh_key       = true
  ssh_private_key_path = var.ssh_private_key_path
  ssh_public_key_path  = var.ssh_public_key_path

  # User Data
  enable_user_data = true
  moltbot_user     = var.moltbot_user
  install_node     = true
  install_moltbot  = true

  # Monitoring
  enable_detailed_monitoring = true
  enable_ssm                 = true

  # Additional Tags
  additional_tags = var.additional_tags
}

# Outputs
output "instance_public_ip" {
  description = "Public IP address of the moltbot instance"
  value       = module.moltbot.instance_public_ip
}

output "ssh_connection_command" {
  description = "Command to SSH into the instance"
  value       = module.moltbot.ssh_connection_command
}

output "ssh_tunnel_command" {
  description = "Command to create SSH tunnel for gateway access"
  value       = module.moltbot.ssh_tunnel_command
}

output "gateway_local_url" {
  description = "URL to access gateway after SSH tunnel"
  value       = module.moltbot.gateway_local_url
}

output "security_reminder" {
  description = "Security best practices reminder"
  value       = module.moltbot.security_reminder
}
MAINEOF

# Replace placeholder
sed -i "s/INSTANCE_NAME_PLACEHOLDER/$INSTANCE_NAME/g" "$INSTANCE_DIR/main.tf"

# Create variables.tf
echo -e "${YELLOW}→${NC} Creating variables.tf"
cat > "$INSTANCE_DIR/variables.tf" <<'EOF'
variable "aws_profile" {
  description = "AWS profile to use"
  type        = string
}

variable "aws_region" {
  description = "AWS region"
  type        = string
}

variable "allowed_ssh_cidr" {
  description = "CIDR block allowed to SSH (your IP)"
  type        = string
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
}

variable "root_volume_size" {
  description = "Root volume size in GB"
  type        = number
}

variable "vpc_cidr" {
  description = "VPC CIDR block"
  type        = string
}

variable "public_subnet_cidr" {
  description = "Public subnet CIDR block"
  type        = string
}

variable "ssh_private_key_path" {
  description = "Path to save SSH private key"
  type        = string
}

variable "ssh_public_key_path" {
  description = "Path to save SSH public key"
  type        = string
}

variable "moltbot_user" {
  description = "Non-root user for running moltbot"
  type        = string
}

variable "gateway_port" {
  description = "Moltbot gateway port"
  type        = number
  default     = 18789
}

variable "additional_tags" {
  description = "Additional tags to apply to resources"
  type        = map(string)
  default     = {}
}
EOF

# Create terraform.tfvars
echo -e "${YELLOW}→${NC} Creating terraform.tfvars"
cat > "$INSTANCE_DIR/terraform.tfvars" <<EOF
# Terraform variables for $INSTANCE_NAME
# IMPORTANT: Update allowed_ssh_cidr with your IP!

aws_profile      = "noldor"
aws_region       = "af-south-1"
allowed_ssh_cidr = "YOUR_IP_HERE/32"  # TODO: Update this!

instance_type    = "t3.small"
root_volume_size = 30

vpc_cidr           = "10.100.0.0/16"
public_subnet_cidr = "10.100.1.0/24"

ssh_private_key_path = "~/.ssh/${INSTANCE_NAME}_key.pem"
ssh_public_key_path  = "~/.ssh/${INSTANCE_NAME}_key.pub"

moltbot_user = "clawd"
gateway_port = 18789

additional_tags = {
  Instance = "$INSTANCE_NAME"
}
EOF

# Create .gitignore
echo -e "${YELLOW}→${NC} Creating .gitignore"
cat > "$INSTANCE_DIR/.gitignore" <<'EOF'
# Terraform
.terraform/
*.tfstate
*.tfstate.*
*.tfstate.backup
.terraform.lock.hcl

# Sensitive
terraform.tfvars

# Backup
crash.log
override.tf
override.tf.json
*_override.tf
*_override.tf.json
EOF

echo ""
echo -e "${GREEN}✓ Instance created: $INSTANCE_NAME${NC}"
echo ""
echo -e "${CYAN}Next steps:${NC}"
echo ""
echo "  1. Edit configuration:"
echo -e "     ${YELLOW}nano $INSTANCE_DIR/terraform.tfvars${NC}"
echo "     → Set your IP address in allowed_ssh_cidr"
echo ""
echo "  2. Initialize Terraform:"
echo -e "     ${YELLOW}./scripts/moltbot $INSTANCE_NAME terraform init${NC}"
echo ""
echo "  3. Deploy infrastructure:"
echo -e "     ${YELLOW}./scripts/moltbot $INSTANCE_NAME terraform apply${NC}"
echo ""
echo "  4. Connect and configure:"
echo -e "     ${YELLOW}./scripts/moltbot $INSTANCE_NAME ssh${NC}"
echo "     sudo -u clawd -i"
echo "     moltbot onboard"
echo ""
echo "  5. Access admin UI:"
echo -e "     ${YELLOW}./scripts/moltbot $INSTANCE_NAME connect${NC}"
echo ""
